# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json
#admin2
Authorization: Token 422c9db45e34005e2140a445e06ed4121defee50
#admin1
#Authorization: Token ad5d06c7fe213a521401e87566daef2ec92a0e14

###

# создание объявления admin1
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token ad5d06c7fe213a521401e87566daef2ec92a0e14

{
  "title": "Автомобиль",
  "description": "Срочно"
}

###

# создание объявления admin2
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 422c9db45e34005e2140a445e06ed4121defee50

{
  "title": "Велосипед",
  "description": "Дорого"
}

###

# попытка поменять объявление admin1
PATCH {{baseUrl}}/advertisements/149/
Content-Type: application/json
Authorization: Token ad5d06c7fe213a521401e87566daef2ec92a0e14

{ 
  "status": "OPEN"
}

###

# попытка поменять объявление admin2
PATCH {{baseUrl}}/advertisements/149/
Content-Type: application/json
Authorization: Token 422c9db45e34005e2140a445e06ed4121defee50

{ 
  "status": "CLOSED"
}

###

# Удаление обьявления admin1
DELETE {{baseUrl}}/advertisements/128/
Content-Type: application/json
Authorization: Token ad5d06c7fe213a521401e87566daef2ec92a0e14 

###

# Удаление обьявления admin2
DELETE {{baseUrl}}/advertisements/118/
Content-Type: application/json
Authorization: Token 422c9db45e34005e2140a445e06ed4121defee50 

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=1
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2022-11-12&status=OPEN
Content-Type: application/json
