# Generated by Django 4.1.1 on 2022-10-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='МОДЕЛЬ')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Стоимость')),
                ('image', models.TextField(verbose_name='МОДЕЛЬ')),
                ('release_date', models.CharField(max_length=15, verbose_name='ДАТА РЕЛИЗА')),
                ('lte_exists', models.BooleanField(verbose_name='LTE')),
                ('slug', models.SlugField(max_length=255, verbose_name='URL')),
            ],
        ),
    ]
